@url = http://localhost:8081
@contentType = application/json

###

POST {{url}}/hero/create HTTP/1.1
Content-Type: {{contentType}}
Authorization: ""

{
    "name": "Artemisa",
    "user": "Duyn",
    "class": "Barbarian"
}

###

GET {{url}}/hero/all/DDuyn HTTP/1.1
###
GET {{url}}/hero/3 HTTP/1.1

###
DELETE {{url}}/hero/delete/10 HTTP/1.1

###
PUT {{url}}/hero/update/3 HTTP/1.1
Content-Type: {{contentType}}
Authorization: ""

{
    "name": "Helena"
}
###
PUT {{url}}/addExperience HTTP/1.1
Content-Type: {{contentType}}
Authorization: ""

{
    "Hero": {
        "Code": 8,
        "Name": "Batman",
        "User": "DDuyn",
        "Class": "Barbarian"
    },
    "HeroStats": {
        "HeroCode": 8,
        "Level": 1,
        "TotalExperience": 0,
        "ExperienceNeeded": 100,
        "Life": 179,
        "Strength": 68,
        "Resistance": 136
    },
    "ExpGained": 100
}

###
GET {{url}}/classes HTTP/1.1